# Generated by Django 5.2.17 on 2026-09-22 18:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
            ],
            options={
                'verbose_name': 'organização',
                'verbose_name_plural': 'organizações',
                'db_table': 'organizacoes',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='OrganizacaoUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('perfil', models.CharField(choices=[('PROPRIETARIO', 'Proprietário'), ('ADMINISTRADOR', 'Administrador'), ('ADVOGADO', 'Advogado'), ('ASSISTENTE', 'Assistente'), ('VISUALIZADOR', 'Visualizador')], default='ADVOGADO', max_length=32, verbose_name='perfil')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('organizacao', models.ForeignKey(db_column='organizacao_id', on_delete=django.db.models.deletion.PROTECT, related_name='membros', to='organizacoes.organizacao', verbose_name='organização')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_organizacao', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'usuário da organização',
                'verbose_name_plural': 'usuários da organização',
                'db_table': 'organizacoes_usuarios',
                'indexes': [models.Index(fields=['organizacao'], name='idx_org_usr_organizacao'), models.Index(fields=['usuario'], name='idx_org_usr_usuario')],
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'usuario'), name='uq_organizacoes_usuarios')],
            },
        ),
    ]
