# Generated by Django 5.2.17 on 2026-09-22 18:39

import apps.contas.managers
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('sobrenome', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso ao admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superusuário')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='último acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'db_table': 'usuarios',
                'ordering': ('nome', 'sobrenome'),
            },
            managers=[
                ('objects', apps.contas.managers.GerenciadorUsuario()),
            ],
        ),
    ]
