# Generated by Django 5.2.17 on 2026-09-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_usuario_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='login'),
        ),
    ]
