# Generated by Django 5.2.17 on 2026-09-22 19:29

import apps.advogados.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('sobrenome', models.CharField(blank=True, max_length=150, verbose_name='sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('cpf', models.CharField(blank=True, max_length=14, validators=[apps.advogados.models.validar_cpf], verbose_name='CPF')),
                ('numero_oab', models.CharField(max_length=8, validators=[apps.advogados.models.validar_numero_oab], verbose_name='número OAB')),
                ('uf_oab', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF da OAB')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='data de atualização')),
                ('organizacao', models.ForeignKey(db_column='organizacao_id', on_delete=django.db.models.deletion.PROTECT, related_name='advogados', to='organizacoes.organizacao', verbose_name='organização')),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis_advogado', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'advogado',
                'verbose_name_plural': 'advogados',
                'db_table': 'advogados',
                'ordering': ('nome', 'sobrenome'),
                'indexes': [models.Index(fields=['organizacao'], name='idx_advogados_organizacao'), models.Index(fields=['numero_oab', 'uf_oab'], name='idx_advogados_oab_uf'), models.Index(fields=['email'], name='idx_advogados_email')],
                'constraints': [models.UniqueConstraint(fields=('organizacao', 'numero_oab', 'uf_oab'), name='uq_advogados_org_oab_uf')],
            },
        ),
    ]
