# Generated by Django 5.2.17 on 2026-09-22 18:39

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('LOGIN_SUCESSO', 'Login com sucesso'), ('LOGIN_FALHA', 'Falha de login'), ('LOGOUT', 'Logout')], max_length=64, verbose_name='ação')),
                ('tipo_entidade', models.CharField(blank=True, max_length=64, verbose_name='tipo da entidade')),
                ('entidade_id', models.UUIDField(blank=True, null=True, verbose_name='id da entidade')),
                ('metadados', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('agente_usuario', models.TextField(blank=True, verbose_name='agente do usuário')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='data de criação')),
            ],
            options={
                'verbose_name': 'log de auditoria',
                'verbose_name_plural': 'logs de auditoria',
                'db_table': 'logs_auditoria',
                'ordering': ('-data_criacao',),
            },
        ),
    ]
