# Generated by Django 5.2.17 on 2026-09-22 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logauditoria',
            name='organizacao',
            field=models.ForeignKey(blank=True, db_column='organizacao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='organizacoes.organizacao', verbose_name='organização'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['organizacao'], name='idx_logs_aud_organizacao'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario'], name='idx_logs_aud_usuario'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['data_criacao'], name='idx_logs_aud_data_criacao'),
        ),
    ]
